### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jfrome** [apiheat/akamai-cli-netlist#3]
**akamai-cli version:** 1.0.2
**.edgerc section:** [default]

After installing, I receive the following error when trying to get network lists:
```
> akamai netlist search get all
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f1fa0]

goroutine 1 [running]:
main.listNetLists(0xc4200beb00, 0xc42012c4d8, 0x6e5e01)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/cmd_list.go:33 +0x140
main.cmdlistNetLists(0xc4200beb00, 0x0, 0xc4200beb00)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/cmd_list.go:12 +0x2b
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.HandleAction(0x73c780, 0x7cd6b0, 0xc4200beb00, 0xc42006e400, 0x0)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.Command.Run(0x7b5cd1, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7b9c08, 0x12, 0x0, ...)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420096d00, 0xc4200be840, 0x0, 0x0)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/app.go:379 +0xa10
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.Command.startApp(0x7b5cef, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7bd0cd, 0x1a, 0x0, ...)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/command.go:298 +0x8d9
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.Command.Run(0x7b5cef, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7bd0cd, 0x1a, 0x0, ...)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/command.go:98 +0x1246
github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli.(*App).Run(0xc4200969c0, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
        /home/travis/gopath/src/github.com/apiheat/akamai-cli-netlist/main.go:291 +0x1b55
```

The issue may have to do with auth, since I get the following error when attempting to search for a netlist:
```
> akamai netlist search --item whitelist
GET https://XXXXXXXXXXXX.luna.akamaiapis.net: 400 The authorization header does not have the right format
```

**Comment by RafPe** [comment]
Hey @jfrome 

We just published updated version of the CLI. Could you do `akamai update` and make sure you are running the most up to date version ? 

Once confirmed you are running the most up to date version you can try to run `akamai netlist --debug debug search --item xxx` which should give us more output

**Comment by RafPe** [comment]
And ;) you can only search by 'IP address' in v1 ( https://developer.akamai.com/api/cloud_security/network_lists/v1.html#searchnetworklists)  

But you can always do *one liner* like I use 
`akamai netlist get all | jq -r '.. | arrays | .[] | select(.name=="whitelist"?)|{"unique-id"}' | jq -r '."unique-id"' | xargs -I % akamai netlist get list --includeElements --id "%" | jq`

**Comment by jfrome** [comment]
I updated to newest version and still see the issue.

Here's debug output:
```
> akamai netlist --debug debug search --item whitelist_jfrome_test
INFO[0000] Create new edge client                        debuglvl=debug path=/home/josh/.edgerc section=default
DEBU[0000] [newClient]::Create new client object        
DEBU[0000] [newClient]::Create credentials              
INFO[0000] Initialize credentials                        edgercConfig=/home/josh/.edgerc edgercSection=default
DEBU[0000] [InitEdgerc]::Loading credentials file       
DEBU[0000] [InitEdgerc]::Loading section from credentials file 
DEBU[0000] [InitEdgerc]::Lookup for credentials ( host/secrets etc) 
DEBU[0000] [InitEdgerc]::Create credentials object      
DEBU[0000] [InitEdgerc]::Map credentials to appropiate object 
DEBU[0000] [InitEdgerc]::Return credentials object      
DEBU[0000] [newClient]::SetBaseURL                      
INFO[0000] Set BaseURL for client                        passThrough=false urlStr=xxxxxxxxxxxxxxxxxx.luna.akamaiapis.net
DEBU[0000] [SetBaseURL]::Base URL set                    baseURL="https://xxxxxxxxxxxxxxxxxx.luna.akamaiapis.net"
DEBU[0000] [newClient]::Create service Auth             
DEBU[0000] [newClient]::Create service NetworkLists     
DEBU[0000] [newClient]::Create service Property         
DEBU[0000] [newClient]::Create service Reporting        
DEBU[0000] [newClient]::Create service A2               
DEBU[0000] [newClient]::Create service IdentityManagement 
DEBU[0000] [newClient]::Create service SiteShield       
DEBU[0000] [newClient]::Create service FRN              
DEBU[0000] [newClient]::Create service Debug            
INFO[0000] Create new request                            base="https://xxxxxxxxxxxxxxxxxx.luna.akamaiapis.net" method=GET path="/network-list/v1/network_lists/search?expression=whitelist_jfrome_test&listType=IP&extended=false&includeDeprecated=false"
DEBU[0000] [NewRequest]::Create http request            
DEBU[0000] [NewRequest]::Set header Authorization       
INFO[0000] Execute http request                         
DEBU[0000] [NewRequest]::Process response               
DEBU[0000] [NewRequest]::Check response                 
DEBU[0000] [CheckResponse]::Check response code         
DEBU[0000] [CheckResponse]::Response code is:400        
DEBU[0000] [CheckResponse]::Create error response object 
DEBU[0000] [CheckResponse]::Read body                   
DEBU[0000] [CheckResponse]::Error body is: {
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/request-error",
  "title": "Bad request",
  "status": 400,
  "detail": "The authorization header does not have the right format",
  "instance": "https://xxxxxxxxxxxxxxxxxx.luna.akamaiapis.net/network-list/v1/network_lists/search?expression=whitelist_jfrome_test&listType=IP&extended=false&includeDeprecated=false",
  "method": "GET",
  "serverIp": "xxxxxxxxxxxxxxxxxx",
  "clientIp": "xxxxxxxxxxxxxxxxxx",
  "requestId": "3c4dcd2",
  "requestTime": "2018-11-12T16:08:10Z"
} 
DEBU[0000] [CheckResponse]::Process response body       
DEBU[0000] [CheckResponse]::Succesfully processed body  
GET https://xxxxxxxxxxxxxxxxxx.luna.akamaiapis.net: 400 The authorization header does not have the right format
```

**Comment by RafPe** [comment]
@jfrome This is really strange - are your credentials are properly formatted ? I just tried your command and it works. 

Also what is your timezone set on your computer to sync with ? 

could you maybe try to install additionally this CLI https://github.com/apiheat/akamai-cli-overview and try to run any of the commands with debug ?

**Comment by jfrome** [comment]
OK, got this sorted.  The issue was a misconfiguration in my .edgerc file.  The [default] section was missing the client_token entry, probably missed it when copying from [papi].  Perhaps a sanity check for .edgerc config items would be useful.  Here's what I from the default Akamai 'property' app when the client_token entry is missing:
```
Missing part of the configuration:

Missing: client_token
```
Thanks for your work on this! It will be very useful.

**Comment by partamonov** [comment]
We updated client with some validations. https://github.com/apiheat/go-edgegrid/pull/13 once we will re-build all CLIs with new version it will be available
